# SPDX-License-Identifier: MIT
# Copyright (c) 2026 TeslaNeuro
# Console static files + proxy to the PlantOS API (long timeouts for compare).
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /simulation/ { proxy_pass http://backend:8000; proxy_read_timeout 600s; }
    location /plant/ { proxy_pass http://backend:8000; }
    location /fault/ { proxy_pass http://backend:8000; proxy_read_timeout 600s; }
    location /results { proxy_pass http://backend:8000; }
    location /health { proxy_pass http://backend:8000; }

    location / {
        try_files $uri /index.html;
    }
}
